// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVqilMuso09zOWteeIzvL-IPAjIWvGstk',
    appId: '1:218969517032:web:35a28b553168e420dcd25d',
    messagingSenderId: '218969517032',
    projectId: 'exploreci',
    authDomain: 'exploreci.firebaseapp.com',
    storageBucket: 'exploreci.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_mdv-lp_t0PEEnSRyzzAEYRUgehvyX2w',
    appId: '1:218969517032:android:d676e5eb0064787fdcd25d',
    messagingSenderId: '218969517032',
    projectId: 'exploreci',
    storageBucket: 'exploreci.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXeziVdrZdJszDPDZh5de5IvfJ5DHHY-I',
    appId: '1:218969517032:ios:5d4bc38a99ae2607dcd25d',
    messagingSenderId: '218969517032',
    projectId: 'exploreci',
    storageBucket: 'exploreci.firebasestorage.app',
    iosBundleId: 'com.domain.exploreci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXeziVdrZdJszDPDZh5de5IvfJ5DHHY-I',
    appId: '1:218969517032:ios:5d4bc38a99ae2607dcd25d',
    messagingSenderId: '218969517032',
    projectId: 'exploreci',
    storageBucket: 'exploreci.firebasestorage.app',
    iosBundleId: 'com.domain.exploreci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVqilMuso09zOWteeIzvL-IPAjIWvGstk',
    appId: '1:218969517032:web:64e2d0f69db464c8dcd25d',
    messagingSenderId: '218969517032',
    projectId: 'exploreci',
    authDomain: 'exploreci.firebaseapp.com',
    storageBucket: 'exploreci.firebasestorage.app',
  );
}
